name: Backup Mensual

on:
  schedule:
    - cron: "0 0 1 * *" # Cada 1 de cada mes
  workflow_dispatch: # Para ejecutarlo manualmente

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Crear archivo ZIP
        run: zip -r backup.zip .

      - name: Subir archivo ZIP como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: backup-mensual
          path: backup.zip
          retention-days: 90 # Puedes cambiarlo
